Base Project MVP Completion
Vroomfrondal/Nasa-CRUD-Gallery pull request #17
Opened 2022-12-05 22:37 UTC by Vroomfrondal

2023-02-15 17:23 UTC, RRamirez1414 reviewed
Super impressed by what you have done as a start! Just by reviewing your code, I can tell you know essential React 🎉

2023-02-15 17:23 UTC, RRamirez1414 commented on src/components/Card.tsx
> +    media = <iframe src={src} title={title ? title : alt} onClick={() => setModalStatus(true)}></iframe>
Sorry, this is a little nitpicky. In certain cases, you can write shorthand versions of ternaries using the OR operator (if the left side is falsy, take the value on the right). I like to write these when I'm sure I can rely on a single default value to fall back on. 
```suggestion
    media = <iframe src={src} title={title || alt} onClick={() => setModalStatus(true)}></iframe>
```

2023-02-15 17:23 UTC, RRamirez1414 commented on src/components/Card.tsx
> +  alt,
Because `title` and `alt` are optional. They have the possibility of rendering "undefined" on your UI if no image or alt value exists. You can assign a default value to a prop and ensure your ternary below will always render a value. Even if it's am empty string. When the `alt` is passed, it will override the default. 
```suggestion
  alt = "",
```

2023-02-15 17:23 UTC, RRamirez1414 commented on src/components/Card.tsx
> +        {media}
Take advantage of JSX to control what elements render while keeping HTML huddled together.
```suggestion
        {media_type === 'video' ? (
          <iframe src={src} title={title ? title : alt} onClick={() => setModalStatus(true)}/>
        ) : (
          <img src={src} alt={alt} onClick={() => setModalStatus(true)}/>
        )}
```

2023-02-15 17:23 UTC, RRamirez1414 commented on src/components/CardModal.tsx
> +  onClose: MouseEventHandler<HTMLElement>
Good use of this type!

2023-02-15 21:09 UTC, Vroomfrondal commented on src/components/NavBar.tsx
> +function useNavBar() {
I ended up going with your above suggestion of picking up the useContext hook. Was pretty intuitive to learn and I see how it avoids prop drilling on a more populated component. But this is also useful, thanks!

2023-02-16 05:46 UTC, Idonoghue requested changes
LOVE your choice of API. Awesome pics. Can tell you have a great passion for animation & styling too 🤭.

I want to say a lot of our feedback is quite nitpicky. And really for personal projects they are pretty much irrelevant. We're gonna try not to bombard you with _every_ little standard we use in coding. However, as we've learned, having strict standards (even imperfect standards) on a large, active repo is required to maintain some sense of sanity.

2023-02-16 05:46 UTC, Idonoghue commented on src/hooks/useFetchImages.ts
> +  useEffect(() => {
Ok we have a doozy of a bug here. We're making a double request of the initial API call. This also duplicates these pics in the list.. It seems to be caused by [this useEffect behavior](https://beta.reactjs.org/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts). I tried to add a cleanup function [using AbortController](https://dmitripavlutin.com/react-cleanup-async-effects/) but it was never working for me for some reason. You can try that if you want. 

Only way I could find to fix was to initialize `needMoreImages` to false. Then have a useEffect inside `HomePage` that calls `setNeedMoreImages(true)` that has an empty dependency array to only run once onMount. 

However this approach causes other bugs because it runs the above useEffect that increments week first so it never loads the most current week's pics. A quick fix to that is to execute the `set__Date`'s inside an `if (isLoading)`

Ping me if you have any questions. We can walkthrough together if you want.

2023-02-16 05:46 UTC, Idonoghue commented on src/components/Pages/HomePage.tsx
> +        if (entries[0].isIntersecting) setNeedMoreImages(true)
Also want to prevent triggering a fetch again when already in a loading state.
```suggestion
        if (!isLoading && entries[0].isIntersecting) setNeedMoreImages(true)
```

2023-02-16 16:58 UTC, Vroomfrondal commented on src/components/Card.tsx
> +
This was super powerful as well as the useContext suggestion. Reduced so many props I didn't consider. Thanks!

2023-02-18 19:52 UTC, Vroomfrondal commented on src/typings/index.d.ts
> +interface ImageTypes {
I too never know if `type Image = {}` in the file or an `interface` possibly in the declaration file is best.  

Thanks for the video, helps clear some stuff up.

2023-02-19 18:48 UTC, Vroomfrondal commented on src/components/NavBar.tsx
> +  }, [activePage])
Wow this was an interesting one. Even with the console log I'm not sure I would've picked up on it. After a bit of reading and a video it does make sense now.

I'm not sure if this is standard in ECG repos, especially for two simple useEffects, but I went ahead and created a custom hook to handle this. My thought being it makes the Nav File a bit easier to read more useEffects:

`const useCloseNavBar = (activePage: string) => {
  const [isShowingLinks, setIsShowingLinks] = useState(false)

  // Close Nav Menu on Scroll
  useEffect(() => {
    window.addEventListener('scroll', () => setIsShowingLinks(false))
    return () => window.removeEventListener('scroll', () => setIsShowingLinks(false)) 
  }, [])

  // Close Nav Menu when switching pages
  useEffect(() => {
    setIsShowingLinks(false)
  }, [activePage])

  return { isShowingLinks, setIsShowingLinks }
}`

2023-02-19 19:05 UTC, Vroomfrondal commented on src/components/NavBar.tsx
> +          <span className="line w-3"></span>
Made me appreciate neat little icon libraries 🤣

2023-02-19 19:23 UTC, Vroomfrondal commented on src/components/ScrollToTopButton.tsx
> +    return () => window.removeEventListener('scroll', toggleVisible)
A second pair of eyes is always helpful 😎

2023-02-19 19:35 UTC, Vroomfrondal commented on src/components/Pages/Favorites.tsx
> +                copyright={image.copyright ? image.copyright : 'NASA'}
I'm not entirely sure why I added fallback logic here other than complexity and not catching it.

Ramon helped me a bit with the destructuring power here and the code has been heavily reduced. After doing so I was able to see more clearly that I was adding fallback logic in the parent and child. Thanks for the heads up!

2023-02-20 16:27 UTC, Idonoghue commented on src/components/NavBar.tsx
> +  }, [activePage])
Yea! In a handful of places we do. This is actually a great instance to use it & I didn't even recognize this. I see this as a hook that's a useState + dependent logic. I would even mimick the useState interface a bit here, for example returning an array instead of an object
```Typescript
  const useIsNavBarOpenState = (activePage: 'Home' | 'Favorites') => {
      const [isShowingLinks, setIsShowingLinks] = useState(false)

        // Close Nav Menu on Scroll
        useEffect(() => {
          window.addEventListener('scroll', () => setIsShowingLinks(false))
          return () => window.removeEventListener('scroll', () => setIsShowingLinks(false))
        }, [])

        // Close Nav Menu when switching pages
        useEffect(() => {
          setIsShowingLinks(false)
        }, [activePage])

        return [ isShowingLinks, setIsShowingLinks ]
  }
}
```

One place we use a similar pattern is `useURLSyncState` which acts as a normal useState except it syncs the state to params stored in the url. Useful to store table filters in url state so you can share links or reload page & it preserves the table filter state.

2023-02-20 20:49 UTC, sabival89 reviewed
I really love the fact that you were able to make out time to complete this project. Great work Sir! 🚀 I tried not to delve deep into your CSS because we use tailwinds anyways but good job on using media queries, animations, transitions etc.  I just have a few comments here and there but your work is looking good so far.

2023-02-20 20:49 UTC, sabival89 commented on src/components/ScrollToTopButton.tsx
> +    else if (scrolled <= 0) setIsVisible(false)
Nice! My suggestion here might be out of scope for this project but Isaac has made me too attentive to "further" simplifying statements like this. You don't have to make the changes but it is just good to know cuz we do it a lot in our codebase.
```suggestion
    setIsVisible((prev) => (scrolled > 150 && !prev) || prev)
```

2023-02-20 20:49 UTC, sabival89 commented on src/styles/index.css
> +}
Whenever the home page is refreshed or loaded for the first time, the horizontal scrollbar is displayed for a second and hidden after the completion of the banner animation. You should hide the x-axis scrollbar to prevent it from showing up.
```suggestion
html {
  display: block;
   overflow-x: hidden;
}
```

2023-02-20 20:49 UTC, sabival89 commented on src/styles/index.css
> +  --modal_blackout: rgba(0, 0, 0, 0.7);
Nice use of CSS variables 🔥

2023-02-20 20:49 UTC, sabival89 commented on src/styles/index.css
> +  font-family: inherit;
There will be no need for this since you have already applied the font-family style to every HTML element on `lines 22-25`
```suggestion
```

2023-02-20 22:50 UTC, Vroomfrondal commented on src/components/Pages/HomePage.tsx
> +  const observer: React.MutableRefObject<any> = useRef()
I admittedly need to get better at these typescript tricks (like the optional chaining tip above as well). 

Other than having to add an optional null type, this worked like a charm. Thanks!
```ts
const observer: React.MutableRefObject<IntersectionObserver | null> = useRef(null)
```

2023-02-21 00:22 UTC, Idonoghue commented on src/components/Pages/HomePage.tsx
> +  const observer: React.MutableRefObject<any> = useRef()
Yea React too is so full of weird Typescript behavior with the builtin hooks. For instance if we send an initial value to useRef it no longer types it as a mutable ref. [This is a good summary](https://dev.to/wojciechmatuszewski/mutable-and-immutable-useref-semantics-with-react-typescript-30c9) of the odd mutable/immutable behavior going on.

Did this work for you? This wasn't giving me any type complaints.
```Typescript
 const observer = useRef<IntersectionObserver>()
```
 I like it slightly better because we're inferring the type from useRef instead of manually annotating which can quickly clutter code.

2023-02-23 01:13 UTC, Vroomfrondal commented on src/components/Pages/HomePage.tsx
> +  const observer: React.MutableRefObject<any> = useRef()
Sorry I should've been more specific in my first reply. I was getting this error: 

`
Type 'MutableRefObject<IntersectionObserver | undefined>' is not assignable to type 'MutableRefObject<IntersectionObserver>'.
`

I figured because the ref didn't have anything assigned at that time, I'd have to use null. What's the best way to handle this scenario?

2023-02-23 01:15 UTC, Vroomfrondal commented on src/components/Pages/HomePage.tsx
> +  const observer: React.MutableRefObject<any> = useRef()
I should've been more specific in my first response. But now i'm seeing the `React.MutableRefObject` Type on the `const` was throwing it off and giving me an error without using `null`. 

Swapping it on the `ref` itself did indeed fix it. Thanks!!

2023-02-23 17:50 UTC, Vroomfrondal commented on src/hooks/useFetchImages.ts
> +  useEffect(() => {
I was able to implement this whole change (very cool how you went through this one, really appreciate it).

I knew that double useEffect() call happened during development, but I didn't realize that was still a red flag so didn't take it as unordinary behavior. I wasn't catching any duplicates after that first call but maybe I just assumed. 

Had I read the corrected code from the get-go, I'm not sure I would've understood why it was written that way adding the `useEffect` and `set_date` logic. In the future I can assume that duplicate useEffect behavior in development means some sort of bug?

2023-02-23 18:06 UTC, Vroomfrondal commented on src/hooks/useFetchImages.ts
> +  useEffect(() => {
Hmm.. interesting one. I was able to implement this whole change but it doesn't seem to still call the new images after the first week because of the `if (isLoading)` logic on the `setDates`. But i'll keep playing with it

I knew that double useEffect() call happened during development, but I didn't realize that was still a red flag so didn't take it as unordinary behavior unless in prod.

In the future I can assume that duplicate useEffect behavior in development means some sort of bug?

2023-03-10 20:58 UTC, Vroomfrondal commented on src/components/Card.tsx
> +          <iframe src={src} title={title || alt} onClick={() => setModalStatus(true)}></iframe>
No I agree! Its packed already with that HTML element ternary so I'll go ahead and swap it out. Nice catch.

2023-03-10 21:48 UTC, Vroomfrondal commented on src/styles/index.css
> +}
This is one of those things I must've just seen so many times it went right over my head. Thanks!

2023-03-29 22:11 UTC, Vroomfrondal commented on src/components/Pages/HomePage.tsx
> +        })}
Nice. The read was very helpful - I'd never put much thought into the keys. 

The downside is in dev mode, with the below duplication useEffect bug we've been discussing, React is throwing "duplicate keys" errors (understandably) when the src is the key. Gives me even more incentive to figure it out, so I see what you mean by technical debt now. Good call, thanks.

2023-03-29 22:23 UTC, Vroomfrondal commented on src/components/Pages/Favorites.tsx
> +                key={index}
Nice. The read was very helpful - I'd never put much thought into the keys.

The downside is in dev mode, with the below duplication useEffect bug we've been discussing, React is throwing "duplicate keys" errors (understandably) when the src is the key. Gives me even more incentive to figure it out, so I see what you mean by technical debt now. Good call, thanks.

2023-04-11 21:05 UTC, Vroomfrondal commented on src/components/Pages/HomePage.tsx
> +        })}
Learning new hooks is always nice. Had to read a bit to understand what's going on with the ForwardRef hook in relation to the ref but I eventually implemented it. Thanks for both tips!

2023-04-12 15:42 UTC, merged